### ISSUE TITLE
Project Objective

### ISSUE THREAD

**Issue by mdroidian** [neezzzy/Final-Project-P100#84]

**Comment by neezzzy** [comment]
The project aims to offer additional opportunities for students to gain valuable experience and build networks with their potential employers. Companies are always looking for new talent. Campus Connect provides a chance to bridge this gap. The idea for Campus Connect was not new, it was inspired by Nayani (2021) and his book for business startups. Our team aimed to create a web application that would allow companies to get to know the students and students to find future employment opportunities. A college student can log in and see different companies that have open projects. Once, the student locates the project that they find interesting they can sign up for it and start working on the project. The student can click and read the details for each project before signing up and maybe find the employer that matches their desired skill level.
