### ISSUE TITLE
Learning Outcomes / Challenges

### ISSUE THREAD

**Issue by mdroidian** [neezzzy/Final-Project-P100#86]
Briefly explain the challenges and learnings My work

**Comment by neezzzy** [comment]
Gain Experience with Express, Mongo DB, React, Bootstrap 

Work on problem solving and debugging 

GitHub Workflow 

Project Management Skills  

Collaboration 

Communication 

Critical Thinking 

Better Comprehension of how Back-End interacts with the Front-End  

Be opened-minded about the different ways to solve one problem  

Have something to add to a personal portfolio that we are proud of 🥇 

Agile Project Management 

Synthesize a bit of each class into the Project
