### ISSUE TITLE
Updated WBS

### ISSUE THREAD

**Issue by mdroidian** [neezzzy/Final-Project-P100#89]
Could be started from #88 

See this from Pardeep's presentations

![image](https://user-images.githubusercontent.com/3792666/205185711-06dec6a6-ffa0-4f57-bd72-902fb60e3945.png)

And from WBS https://www.workbreakdownstructure.com/work-breakdown-structure-examples

![image](https://user-images.githubusercontent.com/3792666/205186139-152062ca-3b87-44d1-a4df-06bf9658e6ba.png)

**Comment by neezzzy** [comment]
updated. 
here is the list of tasks:

- Scope of The Project  
- Determine Project Scope 
- Analysis/Software Requirements 
- Draft preliminary software specifications 
- Design 
- Technical Specifications 
- Functional Requirements 
- Develop Prototype Based on Functional Specifications   
- Development 
- Review Functional Specifications 
- Identify Modular/Tiered Design Patterns   
- Implement MVC 
- Code Development 
- GitHub Branches   
- Testing  
- Test Module Integration 
- Documentation 
- Test Module Integration   
- GitHub Tasks 
- GitHub Project 
- GitHub Pull Request Parties 
- Deployment 
- Merge GitHub Branches into Develop 
- Merge GitHub Branches into Main
