### ISSUE TITLE
Add Stats

### ISSUE THREAD

**Issue by mdroidian** [neezzzy/Final-Project-P100#93]
![image](https://user-images.githubusercontent.com/3792666/205399525-a85a9bce-8689-450e-a2f7-4c012f9fb3f6.png)

**Comment by mdroidian** [comment]
![image](https://user-images.githubusercontent.com/3792666/205399566-405aed50-c59d-4def-ba42-dde649bea2e7.png)

**Comment by mdroidian** [comment]
![image](https://user-images.githubusercontent.com/3792666/205399587-403fe008-e1a2-47b7-a2df-02c2b9651423.png)

**Comment by mdroidian** [comment]
![image](https://user-images.githubusercontent.com/3792666/205399640-501a7b73-76fe-4289-a24c-ef8f7c64795b.png)

**Comment by mdroidian** [comment]
![image](https://user-images.githubusercontent.com/3792666/205399649-c4d9edc9-d684-422d-8405-5f49cd7bdd57.png)

**Comment by mdroidian** [comment]
![image](https://user-images.githubusercontent.com/3792666/205399661-1d3f3497-82c6-485e-a2a3-dcec93b51ea1.png)

**Comment by neezzzy** [comment]
added the stats to the presentation. Thanks, Mike!
